#!/usr/bin/env python

import snmp_helper

ip1 = ('184.105.247.70', 161)
ip2 = ('184.105.247.71', 161)

a_user = 'pysnmp'
auth_key = 'galileo1'
encrypt_key = ' galileo1'

snmp_user = (a_user, auth_key, encrypt_key)


snmp_oids = (
	('sysName', '1.3.6.1.2.1.1.5.0', None),
	('sysUptime', '1.3.6.1.2.1.1.3.0', None),
	('ifDescr', '1.3.6.1.2.1.2.2.1.2.5', None),
	('ifInOcets' '1.3.6.1.2.1.2.2.1.10.5', True),
	('ifInUcstPkts', '1.3.6.1.2.1.2.2.1.11.5', True),
	('ifOutOcets', '1.3.6.1.2.1.2.2.1.16.5', True),
	('ifOutUcstPkts', '1.3.6.1.2.1.2.2.1.17.5', True)
	)
