---
- name: cisco file transfer test
  hosts: pynet-rtr1
  gather_facts: False

  tasks:
  - name: cisco file transfer
    cisco_file_transfer:
      source_file="/home/dbowman/ANSIBLE/cisco.txt"
      dest_file=cisco.txt
      overwrite=true
      enable_scp=true
      host={{ host }}
      port={{ port }}
      username={{ username }}
      password={{ password }}
...