--- 
- name: Exercise1
  hosts: arista

  tasks:
    - name: create VLANs 
      eos_vlan: name={{ item.vlan_name }} vlanid={{ item.vlan_id }}
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {vlan_name: RED, vlan_id: 111}
        - {vlan_name: YELLOW, vlan_id: 222}
        - {vlan_name: BLUE, vlan_id: 333}
...