---
- name: Exercise2
  hosts: arista
  tasks:
    - name: set Ethernet3 description
      eos_interface: name=Ethernet3 description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: "Set Ethernet3 to mode: access and YELLOW vlan"
      eos_switchport: name=Ethernet3 mode=access access_vlan=222
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
...